branch-defaults:
  master:
    environment: RaminSampleConnector
global:
  application_name: sample-connector
  default_ec2_keyname: Ramin_Beanstalk
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
