branch-defaults:
  default:
    environment: RaminEBApp-dev
global:
  application_name: Ramin EB App
  default_ec2_keyname: Ramin_Beanstalk
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: null
